create table cliente (
	idcliente INT,
	morada VARCHAR(50),
	nome VARCHAR(50),
	idade INT,
	genero VARCHAR(50),
	estadocivil VARCHAR(10)
);
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (1, '415 Meadow Ridge Parkway', 'Haskel Courtonne', 55, 'F', 'casado');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (2, '5826 Westend Trail', 'Sanders Blessed', 40, 'M', 'divorciado');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (3, '1 Goodland Lane', 'Pansie Wimes', 46, 'F', 'casado');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (4, '48 Summit Parkway', 'Murdock O''Brogan', 87, 'M', 'solteiro');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (5, '57 Laurel Court', 'Donna Morling', 38, 'M', 'casado');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (6, '578 Superior Court', 'Sherline Delgadillo', 38, 'M', 'solteiro');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (7, '4 Di Loreto Point', 'Valdemar Eldershaw', 83, 'M', 'solteiro');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (8, '6429 Lukken Point', 'Gretta Wisdom', 47, 'M', 'casado');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (9, '0947 Jana Center', 'Flss Steane', 89, 'M', 'divorciado');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (10, '07704 Victoria Trail', 'Adler Frickey', 22, 'F', 'divorciado');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (11, '6543 Ruskin Road', 'Nevins Emeny', 62, 'M', 'casado');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (12, '993 La Follette Road', 'Alicea Sylett', 58, 'M', 'divorciado');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (13, '54481 Fallview Alley', 'Pris Maxted', 53, 'M', 'solteiro');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (14, '6154 Springs Plaza', 'Farr Beardwell', 40, 'M', 'divorciado');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (15, '092 Badeau Hill', 'Rainer Edwick', 77, 'M', 'solteiro');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (16, '7 Bunker Hill Alley', 'Bartel Attenborrow', 83, 'M', 'divorciado');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (17, '6508 Canary Center', 'Sebastian Hast', 90, 'M', 'casado');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (18, '47 Morningstar Terrace', 'Quinta Nazaret', 47, 'M', 'divorciado');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (19, '4 Tomscot Circle', 'Madelin Davinet', 73, 'F', 'divorciado');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (20, '8712 Golf Course Parkway', 'Evelin Keveren', 51, 'F', 'casado');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (21, '7624 Tennyson Park', 'Jo Shiers', 59, 'M', 'divorciado');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (22, '06 Prentice Place', 'Barret Kirkwood', 44, 'F', 'divorciado');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (23, '4 Hovde Center', 'Clarissa Blackham', 80, 'M', 'casado');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (24, '99287 Bay Drive', 'Krista Tommei', 89, 'F', 'divorciado');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (25, '722 Upham Center', 'Lukas McGorley', 21, 'M', 'solteiro');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (26, '62 Twin Pines Drive', 'Viva Maymond', 41, 'M', 'casado');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (27, '74688 Novick Point', 'Brody Points', 29, 'F', 'solteiro');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (28, '0 Northland Trail', 'Minetta Epelett', 22, 'F', 'divorciado');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (29, '8425 Derek Circle', 'Teodorico Harry', 26, 'F', 'casado');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (30, '19409 Upham Parkway', 'Bram St. Ledger', 53, 'M', 'divorciado');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (31, '5381 Tony Lane', 'Abigail Inchcomb', 49, 'M', 'solteiro');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (32, '6 Hagan Center', 'Tisha Tansly', 49, 'M', 'divorciado');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (33, '8548 Pleasure Terrace', 'D''arcy Kellart', 42, 'M', 'divorciado');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (34, '7632 Debra Crossing', 'Heath Barhims', 64, 'M', 'solteiro');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (35, '4087 Northview Junction', 'Quintus Burgott', 86, 'M', 'casado');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (36, '1 Butterfield Avenue', 'Vivie Slobom', 66, 'F', 'casado');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (37, '292 Rowland Plaza', 'Elane Vittle', 40, 'F', 'divorciado');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (38, '2 Graedel Alley', 'Lelah Maddocks', 58, 'M', 'solteiro');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (39, '1 Starling Parkway', 'Brendan Frawley', 34, 'M', 'divorciado');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (40, '487 Sugar Point', 'Cecil Stukings', 23, 'F', 'solteiro');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (41, '63060 Merry Trail', 'Maxy Stallan', 34, 'M', 'solteiro');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (42, '0062 Maywood Crossing', 'Jonathan Rembrant', 39, 'M', 'solteiro');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (43, '8 Tomscot Point', 'Anatole Voller', 80, 'F', 'casado');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (44, '0 Melrose Lane', 'Barris O''Dyvoy', 54, 'M', 'solteiro');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (45, '094 Lillian Junction', 'Whit Lamble', 50, 'M', 'divorciado');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (46, '61779 Texas Court', 'Ivan Cothey', 28, 'F', 'casado');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (47, '1285 Artisan Trail', 'Kerwin Tommasetti', 35, 'M', 'divorciado');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (48, '60 Clemons Place', 'Ashlan Bruna', 39, 'M', 'solteiro');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (49, '453 Declaration Circle', 'Basia Oventon', 54, 'F', 'divorciado');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (50, '99574 Clemons Street', 'Gabriela Hedges', 69, 'F', 'solteiro');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (51, '69243 High Crossing Plaza', 'Alwyn Harbertson', 60, 'M', 'divorciado');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (52, '0767 Vermont Road', 'Lainey Wiggington', 44, 'M', 'solteiro');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (53, '632 Village Green Drive', 'Sarah Teague', 53, 'F', 'solteiro');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (54, '429 Melvin Road', 'Jeddy Sleany', 22, 'M', 'divorciado');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (55, '14873 Kinsman Circle', 'Nata Delhanty', 69, 'F', 'divorciado');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (56, '68667 Thompson Park', 'Henriette Joss', 64, 'M', 'divorciado');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (57, '1 Vernon Pass', 'Tally Riedel', 22, 'M', 'divorciado');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (58, '2 Tomscot Hill', 'Morly Tamsett', 40, 'M', 'divorciado');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (59, '86703 Marcy Hill', 'Teodor Suerz', 18, 'F', 'divorciado');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (60, '0 Larry Point', 'Halley Howsego', 22, 'M', 'divorciado');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (61, '525 Lien Hill', 'Bendix Flett', 21, 'M', 'solteiro');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (62, '36287 Pierstorff Court', 'Bianca Youll', 51, 'M', 'divorciado');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (63, '74 Kings Terrace', 'Olivie Prozescky', 31, 'M', 'casado');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (64, '51 Kipling Junction', 'Pall Davenhall', 82, 'M', 'solteiro');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (65, '97406 Fallview Street', 'Beckie McLugish', 64, 'M', 'solteiro');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (66, '0193 Derek Junction', 'Mireille Placide', 37, 'F', 'casado');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (67, '8 Glendale Alley', 'Krishna Caffery', 86, 'M', 'divorciado');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (68, '537 Kensington Pass', 'Ibby Macek', 50, 'M', 'solteiro');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (69, '0 Clyde Gallagher Way', 'Vitoria Van Der Hoog', 19, 'F', 'divorciado');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (70, '83857 Dryden Parkway', 'Filmore Cassey', 62, 'M', 'divorciado');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (71, '7956 Kedzie Crossing', 'Owen Rooper', 47, 'F', 'solteiro');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (72, '4 Bashford Parkway', 'Pam Feetham', 77, 'M', 'divorciado');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (73, '63663 Meadow Vale Lane', 'Maggie Purves', 77, 'M', 'casado');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (74, '9 Columbus Center', 'Myles Clarricoates', 57, 'F', 'solteiro');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (75, '831 Browning Court', 'Alexandrina Oxenbury', 64, 'F', 'solteiro');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (76, '573 Dahle Pass', 'Rudie Zanicchelli', 31, 'F', 'casado');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (77, '70 Fairview Street', 'Ellyn Truckell', 67, 'F', 'casado');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (78, '24943 Truax Lane', 'Cassey Lomasna', 67, 'F', 'divorciado');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (79, '421 Daystar Point', 'Bobbi Wythill', 31, 'M', 'casado');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (80, '5758 Stone Corner Crossing', 'Berenice Dorre', 65, 'M', 'solteiro');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (81, '8 Rutledge Center', 'Giorgia Humfrey', 55, 'F', 'casado');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (82, '22879 Eastlawn Hill', 'Marion Blinckhorne', 57, 'F', 'divorciado');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (83, '65 Kenwood Road', 'Keenan Kopelman', 39, 'F', 'divorciado');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (84, '45 Drewry Trail', 'Steffie Boatwright', 18, 'M', 'solteiro');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (85, '25608 Fairview Terrace', 'Alfi Gilliard', 54, 'M', 'casado');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (86, '4109 Clove Avenue', 'Jeth Rosbottom', 23, 'F', 'casado');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (87, '9590 North Place', 'Nico Witterick', 45, 'F', 'solteiro');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (88, '3 Bonner Plaza', 'Arleen Trett', 87, 'F', 'solteiro');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (89, '260 Huxley Court', 'Freemon Rosini', 27, 'M', 'solteiro');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (90, '71633 Butterfield Trail', 'Jakob Nitto', 29, 'F', 'solteiro');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (91, '24854 Di Loreto Place', 'Inga Tooley', 68, 'M', 'divorciado');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (92, '5 Ruskin Point', 'Sallyann O''Lennachain', 82, 'F', 'casado');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (93, '4 New Castle Junction', 'Tan Nolte', 67, 'F', 'divorciado');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (94, '0 Westridge Alley', 'Artair Macklam', 23, 'M', 'solteiro');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (95, '27831 Pawling Court', 'Willi Houndsom', 34, 'F', 'solteiro');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (96, '34023 Northridge Hill', 'Domingo Warmington', 47, 'F', 'solteiro');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (97, '36982 Mayfield Terrace', 'Inglebert Hansard', 66, 'F', 'solteiro');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (98, '1918 Commercial Street', 'Joaquin Alvarez', 61, 'F', 'divorciado');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (99, '6 Gateway Junction', 'Sean Roscow', 36, 'F', 'divorciado');
insert into cliente (idcliente, morada, nome, idade, genero, estadocivil) values (100, '44684 Manitowish Center', 'Kittie Aykroyd', 87, 'F', 'divorciado');
